[project]
name = "article-rabbitmq"
version = "0.1.0"
description = "Async RabbitMQ Articles"
authors = [
    {name = "Elysson MR",email = "elyssonmr@gmail.com"}
]
readme = "README.md"
requires-python = "3.14"
dependencies = [
    "aio-pika (>=9.6.1,<10.0.0)",
    "pydantic (>=2.12.5,<3.0.0)",
    "fastapi[standard] (>=0.136.3,<0.137.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
